title: "Donna Behr PT & Pilates"
author: "Donna Behr Physical Therapy, LLC"
description: "Donna Behr Physical Therapy & Pilates"
more: "read more"

url: "https://donnabehrpt.com"
# baseurl: "/contrast" # comment out if in root directory

style:
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"


# note that ths uses "Font Awesome" icons
# http://fortawesome.github.io/Font-Awesome/icons/
links:
  # - linkedin: "http://www.linkedin.com/in/aaronbehr1"
  # - github: "https://github.com/abehr/"
  # - bitbucket: "https://bitbucket.org/abehr/"
  # - twitter: "https://twitter.com/aaronbehr1/"
  # - reddit: "https://www.reddit.com/u/aber1/"
  # - facebook: "https://www.facebook.com/aaronbehr"
  # - youtube: "https://www.youtube.com/user/aaronbehr1"
  # - google-plus: "https://plus.google.com/+me"
  # - steam: "http://steamcommunity.com/id/me/"

# note that I don't have my email here because I needed to do the recaptcha thing.
# it's hard-coded into the layout file

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
